
Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"

  config.vm.network "private_network", ip: "192.168.10.3"

  config.vm.hostname = "kube-node1"

  config.vm.provider "virtualbox" do |vb|

     vb.memory = "1500"

  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum -y update
    sudo systemctl stop firewalld
    sudo systemctl disable firewalld
    sudo yum -y install ntp
    sudo systemctl start ntpd
    sudo systemctl enable ntpd

    $config=`cat << EOF > /etc/hosts
    192.168.10.2   kube-master
    192.168.10.3   kube-node1
    192.168.10.4   kube-node2
    EOF`

    sudo yum -y install flannel kubernetes

    $config2=`cat << EOF > /etc/sysconfig/flanneld
    FLANNEL_ETCD="http://kube-master:2379"
    FLANNEL_ETCD_KEY="/atomic.io/network"
    EOF`

    $config3=`cat << EOF > /etc/kubernetes/config
    KUBE_LOGTOSTDERR="--logtostderr=true"
    KUBE_LOG_LEVEL="--v=0"
    KUBE_ALLOW_PRIV="--allow_privileged=false"
    KUBE_MASTER="--master=http://kube-master:8080"
    EOF`

    $config3=`cat << EOF > /etc/kubernetes/kubelet
    KUBELET_ADDRESS="--address=0.0.0.0"
    KUBELET_PORT="--port=10250"
    KUBELET_HOSTNAME="--hostname_override=kube-node2"
    KUBELET_API_SERVER="--api_servers=http://kube-master:8080"
    KUBELET_ARGS=""
    EOF`

    for SERVICES in kube-proxy kubelet docker flanneld; do
      sudo systemctl restart $SERVICES
      sudo systemctl enable $SERVICES
      sudo systemctl status $SERVICES
    done
  SHELL
end
